/* Old Testament Quiz — question bank
   Pack 1 · 85 questions
   Every `ref` and `quote` is verified verbatim against the KJV text.
   Shape: { id, book, section, difficulty, q, options[4], answer(index), explain, ref, quote? }
*/
window.QUESTION_BANK = [

/* ── GENESIS ───────────────────────────────────────────── */
{id:"gen-001",book:"Genesis",section:"Torah",difficulty:"easy",
 q:"What are the first words God speaks in Scripture?",
 options:["\u201cBe fruitful, and multiply\u201d","\u201cLet there be light\u201d","\u201cLet us make man in our image\u201d","\u201cIt is not good that the man should be alone\u201d"],
 answer:1,
 explain:"Creation begins with speech, and the first spoken word is light. The other three are all genuine divine sayings in Genesis, but each comes later \u2014 the image of God and the blessing to multiply in chapter 1, and man's aloneness in chapter 2.",
 ref:"Genesis 1:3", quote:"And God said, Let there be light: and there was light."},

{id:"gen-002",book:"Genesis",section:"Torah",difficulty:"easy",
 q:"Which tree in Eden was forbidden?",
 options:["The tree of life","The tree of knowledge of good and evil","The fig tree","The tree in the midst of the river"],
 answer:1,
 explain:"The tree of life was never forbidden before the fall \u2014 access to it was cut off only afterward, when the man was driven out and cherubim were set to guard the way to it.",
 ref:"Genesis 2:17", quote:"But of the tree of the knowledge of good and evil, thou shalt not eat of it"},

{id:"gen-003",book:"Genesis",section:"Torah",difficulty:"medium",
 q:"What was the fruit of the forbidden tree?",
 options:["An apple","A fig","A pomegranate","The text never says"],
 answer:3,
 explain:"Genesis never identifies the fruit. The apple entered Western tradition largely through Latin wordplay \u2014 malum means both \u2018evil\u2019 and \u2018apple\u2019 \u2014 and through later art and poetry, not the text.",
 ref:"Genesis 3:6"},

{id:"gen-004",book:"Genesis",section:"Torah",difficulty:"medium",
 q:"What did the serpent tell the woman would happen if she ate?",
 options:["She would gain the whole earth","She would not surely die, and would be as gods, knowing good and evil","She would live forever","God would be pleased with her boldness"],
 answer:1,
 explain:"The lie works by mixing truth with denial: their eyes were indeed opened, but the promised exemption from death was false.",
 ref:"Genesis 3:4-5", quote:"Ye shall not surely die"},

{id:"gen-005",book:"Genesis",section:"Torah",difficulty:"medium",
 q:"What did Cain and Abel each bring as an offering?",
 options:["Cain brought fruit of the ground; Abel brought firstlings of his flock","Both brought grain","Cain brought a lamb; Abel brought grain","Both brought animals from their herds"],
 answer:0,
 explain:"Cain was a tiller of the ground and Abel a keeper of sheep, so each brought from his own labour. The text notes that Abel brought of the firstlings and of the fat \u2014 the best portions.",
 ref:"Genesis 4:3-4"},

{id:"gen-006",book:"Genesis",section:"Torah",difficulty:"medium",
 q:"What was Cain's punishment for killing Abel?",
 options:["Immediate death","The ground would no longer yield to him, and he would be a fugitive and a vagabond","Blindness","Enslavement to Seth"],
 answer:1,
 explain:"The curse fits the crime: the ground that received Abel's blood refuses Cain its strength. God also set a mark on Cain to prevent anyone from killing him \u2014 a protection, not a punishment.",
 ref:"Genesis 4:12", quote:"a fugitive and a vagabond shalt thou be in the earth"},

{id:"gen-007",book:"Genesis",section:"Torah",difficulty:"hard",
 q:"Who is recorded as walking with God and not seeing death, being taken by God?",
 options:["Methuselah","Enoch","Lamech","Jared"],
 answer:1,
 explain:"Enoch walked with God for three hundred years and then was not, because God took him. Methuselah is the long-lived one (969 years) and is often confused with him.",
 ref:"Genesis 5:24", quote:"And Enoch walked with God: and he was not; for God took him."},

{id:"gen-008",book:"Genesis",section:"Torah",difficulty:"medium",
 q:"Which bird did Noah send out of the ark first?",
 options:["A dove","A raven","A sparrow","An eagle"],
 answer:1,
 explain:"The raven went first and kept going to and fro. Only afterward did Noah send the dove, which returned, then brought back an olive leaf, then did not return at all.",
 ref:"Genesis 8:7"},

{id:"gen-009",book:"Genesis",section:"Torah",difficulty:"easy",
 q:"What was the sign of God's covenant after the flood?",
 options:["Circumcision","The rainbow","The Sabbath","An altar of unhewn stone"],
 answer:1,
 explain:"The bow in the cloud is the token of a covenant made with Noah and with every living creature \u2014 universal in scope. Circumcision comes later and is specific to Abraham's line.",
 ref:"Genesis 9:13", quote:"I do set my bow in the cloud, and it shall be for a token of a covenant between me and the earth."},

{id:"gen-010",book:"Genesis",section:"Torah",difficulty:"medium",
 q:"Why did God confound the language at Babel?",
 options:["The people worshipped idols there","The people sought to build a city and tower to make themselves a name, and would be restrained in nothing","They refused to offer sacrifice","They murdered their king"],
 answer:1,
 explain:"The stated motive is self-exaltation and refusal to be scattered. Idolatry and violence are not mentioned; the concern is unchecked human ambition.",
 ref:"Genesis 11:4-6", quote:"let us make us a name, lest we be scattered abroad upon the face of the whole earth"},

{id:"gen-011",book:"Genesis",section:"Torah",difficulty:"medium",
 q:"From what city did Abram originally set out?",
 options:["Haran","Ur of the Chaldees","Damascus","Shechem"],
 answer:1,
 explain:"Terah took the family from Ur toward Canaan, but they settled in Haran, where Terah died. Abram's call in chapter 12 sends him onward from Haran \u2014 so Haran is a real stop, but not the origin.",
 ref:"Genesis 11:31"},

{id:"gen-012",book:"Genesis",section:"Torah",difficulty:"hard",
 q:"Who was Melchizedek?",
 options:["King of Sodom","King of Salem and priest of the most high God","A captain in Abram's household","Lot's father-in-law"],
 answer:1,
 explain:"He brings out bread and wine and blesses Abram, who gives him a tenth of everything. The king of Sodom appears in the same chapter, which is where the confusion usually comes from.",
 ref:"Genesis 14:18", quote:"And Melchizedek king of Salem brought forth bread and wine: and he was the priest of the most high God."},

{id:"gen-013",book:"Genesis",section:"Torah",difficulty:"medium",
 q:"What did God count to Abram for righteousness?",
 options:["His obedience in leaving Ur","His belief in the LORD","His tithe to Melchizedek","His willingness to offer Isaac"],
 answer:1,
 explain:"After being shown the stars and promised descendants beyond counting, Abram believed \u2014 and it was reckoned as righteousness. This verse becomes central to Paul's argument in Romans and Galatians.",
 ref:"Genesis 15:6", quote:"And he believed in the LORD; and he counted it to him for righteousness."},

{id:"gen-014",book:"Genesis",section:"Torah",difficulty:"easy",
 q:"What was the sign of the covenant God gave Abraham?",
 options:["Circumcision","The rainbow","A new name for Sarah alone","The binding of Isaac"],
 answer:0,
 explain:"Every male was to be circumcised as a token in the flesh. Abram and Sarai were both renamed in the same chapter, but the covenant sign is circumcision.",
 ref:"Genesis 17:11", quote:"And ye shall circumcise the flesh of your foreskin; and it shall be a token of the covenant betwixt me and you."},

{id:"gen-015",book:"Genesis",section:"Torah",difficulty:"medium",
 q:"What happened to Lot's wife?",
 options:["She was struck blind","She became a pillar of salt","She returned to Sodom and perished there","She was taken captive"],
 answer:1,
 explain:"She looked back from behind him and became a pillar of salt \u2014 a single verse, easy to overlook, but one Jesus later invokes as a warning.",
 ref:"Genesis 19:26", quote:"But his wife looked back from behind him, and she became a pillar of salt."},

{id:"gen-016",book:"Genesis",section:"Torah",difficulty:"medium",
 q:"What did Abraham find caught in a thicket on Mount Moriah?",
 options:["A lamb","A ram caught by his horns","A goat","A young bullock"],
 answer:1,
 explain:"Abraham had told Isaac that God would provide himself a lamb \u2014 but what was actually provided was a ram caught by its horns. The distinction is easy to miss.",
 ref:"Genesis 22:13", quote:"and behold behind him a ram caught in a thicket by his horns"},

{id:"gen-017",book:"Genesis",section:"Torah",difficulty:"medium",
 q:"What did Esau receive in exchange for his birthright?",
 options:["A field near Hebron","Bread and pottage of lentiles","Silver and cattle","A blessing from Isaac"],
 answer:1,
 explain:"Esau came in faint from the field and traded the birthright for a meal, then rose up and went his way \u2014 the text's own verdict is that he despised his birthright.",
 ref:"Genesis 25:34", quote:"Then Jacob gave Esau bread and pottage of lentiles"},

{id:"gen-018",book:"Genesis",section:"Torah",difficulty:"medium",
 q:"How did Jacob obtain the blessing meant for Esau?",
 options:["He won it in a contest","He disguised himself with goat skins before his blind father","He purchased it with silver","Isaac named him heir openly"],
 answer:1,
 explain:"Rebekah put the skins of the kids on his hands and neck so that the blind Isaac would feel Esau's hairiness. The birthright sale was a separate, earlier transaction.",
 ref:"Genesis 27:16"},

{id:"gen-019",book:"Genesis",section:"Torah",difficulty:"medium",
 q:"What did Jacob see in his dream at Bethel?",
 options:["A burning bush","A ladder set up on the earth reaching to heaven, with angels ascending and descending","Seven fat and seven lean cattle","A wheel within a wheel"],
 answer:1,
 explain:"He named the place Bethel, \u2018house of God.\u2019 The cattle belong to Pharaoh's dream, the bush to Moses, and the wheels to Ezekiel.",
 ref:"Genesis 28:12", quote:"and behold a ladder set up on the earth, and the top of it reached to heaven"},

{id:"gen-020",book:"Genesis",section:"Torah",difficulty:"medium",
 q:"After wrestling until the breaking of the day, what new name was Jacob given?",
 options:["Israel","Jeshurun","Abimelech","Peniel"],
 answer:0,
 explain:"He was renamed Israel because he had power with God and with men and prevailed. Peniel is the name he gave the place, not himself.",
 ref:"Genesis 32:28", quote:"Thy name shall be called no more Jacob, but Israel"},

{id:"gen-021",book:"Genesis",section:"Torah",difficulty:"hard",
 q:"What did Joseph's brothers do with him before he reached Egypt?",
 options:["Left him bound in the wilderness","Cast him into a pit, then sold him to passing merchants","Sold him directly to Potiphar","Abandoned him in Shechem"],
 answer:1,
 explain:"They stripped him of his coat and cast him into an empty pit, then sold him for twenty pieces of silver to a passing company. Potiphar buys him only after he arrives in Egypt.",
 ref:"Genesis 37:24"},

{id:"gen-022",book:"Genesis",section:"Torah",difficulty:"medium",
 q:"How did Joseph describe his brothers' actions when he finally revealed himself?",
 options:["\u201cThe LORD will repay you as you deserve\u201d","\u201cYe thought evil against me; but God meant it unto good\u201d","\u201cLet us never speak of this again\u201d","\u201cYe have shamed our father's house\u201d"],
 answer:1,
 explain:"Joseph names the wrong plainly \u2014 it was evil intent \u2014 while holding that God's purpose ran through it. He does not excuse the brothers; he reframes the outcome.",
 ref:"Genesis 50:20", quote:"ye thought evil against me; but God meant it unto good"},

/* ── EXODUS ────────────────────────────────────────────── */
{id:"exo-001",book:"Exodus",section:"Torah",difficulty:"easy",
 q:"Who drew the infant Moses out of the river?",
 options:["Pharaoh's daughter","Miriam","Jochebed","A Hebrew midwife"],
 answer:0,
 explain:"Pharaoh's daughter found the ark of bulrushes and adopted him. Miriam, his sister, watched from a distance and arranged for his own mother to nurse him \u2014 but the drawing out was Pharaoh's daughter's act, and she gave him his name.",
 ref:"Exodus 2:5-10"},

{id:"exo-002",book:"Exodus",section:"Torah",difficulty:"medium",
 q:"Where did Moses flee after killing the Egyptian?",
 options:["Midian","Edom","Cush","Canaan"],
 answer:0,
 explain:"He fled to Midian, sat down by a well, defended the daughters of the priest of Midian, and married Zipporah.",
 ref:"Exodus 2:15"},

{id:"exo-003",book:"Exodus",section:"Torah",difficulty:"medium",
 q:"What was Moses doing when he saw the burning bush?",
 options:["Fleeing Pharaoh's soldiers","Keeping the flock of his father-in-law","Praying alone on the mountain","Traveling to Egypt with Aaron"],
 answer:1,
 explain:"He was shepherding Jethro's flock and led it to the back side of the desert, to Horeb. The call comes in the middle of ordinary work, not during a crisis or a devotional retreat.",
 ref:"Exodus 3:1"},

{id:"exo-004",book:"Exodus",section:"Torah",difficulty:"easy",
 q:"How did God answer when Moses asked for his name?",
 options:["\u201cI AM THAT I AM\u201d","\u201cThe God of hosts\u201d","\u201cEl Shaddai\u201d","\u201cThe Holy One of Israel\u201d"],
 answer:0,
 explain:"The name is bound up with the verb \u2018to be,\u2019 and connects to the divine name YHWH. God Almighty \u2014 El Shaddai \u2014 is a real name used of God, and appears just one chapter later, where God says the patriarchs knew him by it but not by his name YHWH.",
 ref:"Exodus 3:14", quote:"And God said unto Moses, I AM THAT I AM"},

{id:"exo-005",book:"Exodus",section:"Torah",difficulty:"medium",
 q:"What was the first plague on Egypt?",
 options:["Frogs","The waters turned to blood","Darkness","Flies"],
 answer:1,
 explain:"Aaron's rod struck the Nile and its waters became blood, killing the fish. Frogs follow as the second plague.",
 ref:"Exodus 7:20"},

{id:"exo-006",book:"Exodus",section:"Torah",difficulty:"hard",
 q:"At which plague did Pharaoh's magicians fail and say \u201cThis is the finger of God\u201d?",
 options:["Blood","Frogs","Lice","Hail"],
 answer:2,
 explain:"The magicians duplicated blood and frogs, but could not bring forth lice \u2014 and that is where they conceded. It is the turning point in the contest.",
 ref:"Exodus 8:19", quote:"Then the magicians said unto Pharaoh, This is the finger of God"},

{id:"exo-007",book:"Exodus",section:"Torah",difficulty:"medium",
 q:"What kind of lamb was required for the Passover?",
 options:["A female of the second year","A male of the first year, without blemish","Any lamb from the flock","The firstborn of the herd"],
 answer:1,
 explain:"The lamb was to be without blemish, a male of the first year, taken from the sheep or the goats \u2014 the goat option is frequently forgotten.",
 ref:"Exodus 12:5", quote:"Your lamb shall be without blemish, a male of the first year"},

{id:"exo-008",book:"Exodus",section:"Torah",difficulty:"easy",
 q:"What did the blood on the doorposts accomplish?",
 options:["It marked houses for the Egyptians to avoid","It caused the LORD to pass over that house so the destroyer would not enter","It consecrated the firstborn sons","It sealed the covenant with Abraham"],
 answer:1,
 explain:"The blood was a token on the houses; seeing it, the LORD passed over and would not suffer the destroyer to come in. It functions as protection, not as a signal to human enemies.",
 ref:"Exodus 12:13", quote:"and when I see the blood, I will pass over you"},

{id:"exo-009",book:"Exodus",section:"Torah",difficulty:"medium",
 q:"How did God lead Israel through the wilderness?",
 options:["By the staff of Aaron","By a pillar of cloud by day and a pillar of fire by night","By twelve tribal standards","By dreams given nightly to Moses"],
 answer:1,
 explain:"The pillar went before them and did not depart, giving both guidance and light. It later stands between Israel and the Egyptian army at the sea.",
 ref:"Exodus 13:21"},

{id:"exo-010",book:"Exodus",section:"Torah",difficulty:"hard",
 q:"By what means were the waters of the sea divided?",
 options:["A strong east wind, while Moses stretched out his hand","A blast from the silver trumpets","An earthquake","Aaron's rod striking the water"],
 answer:0,
 explain:"Moses stretched out his hand, and the LORD caused the sea to go back by a strong east wind all that night. The wind is explicit in the text and often dropped from retellings.",
 ref:"Exodus 14:21", quote:"and the LORD caused the sea to go back by a strong east wind all that night"},

{id:"exo-011",book:"Exodus",section:"Torah",difficulty:"medium",
 q:"What did God provide when the people complained of hunger?",
 options:["Quail and manna","Water from the rock","Grain purchased from Midian","Fruit from the oasis at Elim"],
 answer:0,
 explain:"Quail covered the camp in the evening and manna appeared in the morning. Water from the rock answers a different complaint, in the next chapter.",
 ref:"Exodus 16:13"},

{id:"exo-012",book:"Exodus",section:"Torah",difficulty:"hard",
 q:"Who held up Moses' hands during the battle with Amalek?",
 options:["Joshua and Caleb","Aaron and Hur","Nadab and Abihu","Eleazar and Ithamar"],
 answer:1,
 explain:"Aaron and Hur stayed up his hands, one on each side, while Joshua fought below. Joshua is present in the story \u2014 but on the battlefield, not on the hill.",
 ref:"Exodus 17:12", quote:"and Aaron and Hur stayed up his hands, the one on the one side, and the other on the other side"},

{id:"exo-013",book:"Exodus",section:"Torah",difficulty:"medium",
 q:"What did Jethro advise Moses to do?",
 options:["Return with him to Midian","Appoint able men as rulers to judge smaller matters","Build an altar at Rephidim","Send spies ahead into Canaan"],
 answer:1,
 explain:"Seeing Moses judging alone from morning to evening, Jethro warned he would wear away, and proposed rulers of thousands, hundreds, fifties, and tens \u2014 delegation with an appeals structure.",
 ref:"Exodus 18:21"},

{id:"exo-014",book:"Exodus",section:"Torah",difficulty:"medium",
 q:"What did the people do while Moses was on the mountain?",
 options:["Fled back toward Egypt","Made and worshipped a golden calf","Appointed a new leader","Attacked the Amalekites"],
 answer:1,
 explain:"Aaron collected their golden earrings and fashioned the calf, then built an altar and proclaimed a feast to the LORD \u2014 the sin is not the abandonment of God's name, but the worship of him through an image.",
 ref:"Exodus 32:4"},

{id:"exo-015",book:"Exodus",section:"Torah",difficulty:"medium",
 q:"How does the book of Exodus end?",
 options:["Israel enters Canaan","Moses dies","The glory of the LORD fills the finished tabernacle","The first Passover is celebrated"],
 answer:2,
 explain:"The cloud covered the tent and the glory filled the tabernacle, so that Moses could not enter. Moses' death closes Deuteronomy, not Exodus.",
 ref:"Exodus 40:34", quote:"and the glory of the LORD filled the tabernacle"},

/* ── LEVITICUS ─────────────────────────────────────────── */
{id:"lev-001",book:"Leviticus",section:"Torah",difficulty:"easy",
 q:"Which repeated command sums up the central theme of Leviticus?",
 options:["\u201cBe fruitful, and multiply\u201d","\u201cYe shall be holy: for I the LORD your God am holy\u201d","\u201cFear not, for I am with thee\u201d","\u201cRemember the sabbath day\u201d"],
 answer:1,
 explain:"Holiness \u2014 separateness for God's use \u2014 is the organizing idea of the whole book, governing sacrifice, diet, sexuality, festivals, and land.",
 ref:"Leviticus 19:2", quote:"Ye shall be holy: for I the LORD your God am holy."},

{id:"lev-002",book:"Leviticus",section:"Torah",difficulty:"medium",
 q:"Why did Nadab and Abihu die?",
 options:["They ate of the shewbread","They offered strange fire before the LORD, which he commanded them not","They touched the ark","They refused to enter the tent of meeting"],
 answer:1,
 explain:"Fire went out from the LORD and devoured them. The eating of shewbread belongs to David at Nob; touching the ark is Uzzah's death, in 2 Samuel.",
 ref:"Leviticus 10:1", quote:"and offered strange fire before the LORD, which he commanded them not"},

{id:"lev-003",book:"Leviticus",section:"Torah",difficulty:"medium",
 q:"On the Day of Atonement, what happened to the second goat?",
 options:["Burned outside the camp","Eaten by the priests","Sent alive into the wilderness bearing the people's iniquities","Released into the Jordan"],
 answer:2,
 explain:"The scapegoat carried the confessed sins away into a land not inhabited. The first goat was killed as a sin offering \u2014 two goats, two distinct fates.",
 ref:"Leviticus 16:21-22"},

{id:"lev-004",book:"Leviticus",section:"Torah",difficulty:"hard",
 q:"What did the high priest do on the Day of Atonement that was permitted only once a year?",
 options:["Offered a burnt offering","Wore the ephod","Entered within the veil, into the most holy place","Blew the silver trumpets"],
 answer:2,
 explain:"Entry behind the veil was restricted to this one day, and even then only with blood and a cloud of incense. The ephod was ordinary priestly dress; burnt offerings were daily.",
 ref:"Leviticus 16:2"},

{id:"lev-005",book:"Leviticus",section:"Torah",difficulty:"medium",
 q:"What two marks made a land animal clean?",
 options:["Fins and scales","Chewing the cud and a divided hoof","Being born within the flock","Being under one year old"],
 answer:1,
 explain:"Both marks were required together, which is why the camel, coney, hare, and swine are each named as failing on one count. Fins and scales are the test for water creatures.",
 ref:"Leviticus 11:3", quote:"Whatsoever parteth the hoof, and is clovenfooted, and cheweth the cud, among the beasts, that shall ye eat."},

{id:"lev-006",book:"Leviticus",section:"Torah",difficulty:"medium",
 q:"What reason does Leviticus give for blood making atonement?",
 options:["Blood is costly","The life of the flesh is in the blood","Blood cleanses metal and cloth","Blood was forbidden as food"],
 answer:1,
 explain:"Life belongs to God, and the blood carries the life \u2014 which is also why eating blood is prohibited. This verse is the theological hinge of the sacrificial system.",
 ref:"Leviticus 17:11", quote:"For the life of the flesh is in the blood"},

{id:"lev-007",book:"Leviticus",section:"Torah",difficulty:"easy",
 q:"Which command from Leviticus did Jesus later call the second greatest?",
 options:["\u201cThou shalt not bear false witness\u201d","\u201cThou shalt love thy neighbour as thyself\u201d","\u201cHonour thy father and thy mother\u201d","\u201cYe shall keep my sabbaths\u201d"],
 answer:1,
 explain:"It sits in the middle of a chapter of practical social law \u2014 wages, gleaning, honest weights \u2014 which is part of its force. The other three are commandments, but from the Decalogue in Exodus and Deuteronomy.",
 ref:"Leviticus 19:18", quote:"thou shalt love thy neighbour as thyself"},

{id:"lev-008",book:"Leviticus",section:"Torah",difficulty:"medium",
 q:"What happened in the Year of Jubilee?",
 options:["All warfare ceased","Ancestral land returned to its families and Hebrew servants went free","A new high priest was installed","The tabernacle was rebuilt"],
 answer:1,
 explain:"Proclaimed every fiftieth year, it prevented permanent accumulation of land \u2014 property was effectively leased until the next Jubilee, never sold outright.",
 ref:"Leviticus 25:10", quote:"proclaim liberty throughout all the land unto all the inhabitants thereof"},

{id:"lev-009",book:"Leviticus",section:"Torah",difficulty:"hard",
 q:"What was Israel commanded to do in the seventh year?",
 options:["Let the land rest and lie fallow","Double the tithe","Fast for a full month","Take a national census"],
 answer:0,
 explain:"A sabbath of rest for the land itself \u2014 no sowing or pruning. The later exile is explained in Chronicles as the land finally enjoying the sabbaths it had been denied.",
 ref:"Leviticus 25:4"},

{id:"lev-010",book:"Leviticus",section:"Torah",difficulty:"hard",
 q:"What did the law of gleaning require of harvesters?",
 options:["To tithe a tenth of the harvest to the priests","To leave the corners of the field and the fallen grapes for the poor and the stranger","To rest every third day of harvest","To burn the first sheaf on the altar"],
 answer:1,
 explain:"Not charity from surplus but a structural claim on the harvest itself \u2014 the poor gathered for themselves. This law is the setting of the book of Ruth.",
 ref:"Leviticus 19:9-10"},

/* ── NUMBERS ───────────────────────────────────────────── */
{id:"num-001",book:"Numbers",section:"Torah",difficulty:"medium",
 q:"Which two spies urged Israel to go up and take the land?",
 options:["Joshua and Caleb","Aaron and Hur","Eldad and Medad","Dathan and Abiram"],
 answer:0,
 explain:"Ten brought an evil report; Joshua and Caleb rent their clothes and dissented. Dathan and Abiram are rebels in the Korah episode, and Eldad and Medad prophesied in the camp.",
 ref:"Numbers 14:6-7"},

{id:"num-002",book:"Numbers",section:"Torah",difficulty:"medium",
 q:"How long did Israel wander, and on what basis was the number set?",
 options:["Twelve years, one per tribe","Forty years, a year for each day the spies searched the land","Seventy years, matching the later exile","Seven years, one per day of creation"],
 answer:1,
 explain:"The sentence is calibrated to the offence: forty days of spying became forty years of wandering, until that generation fell in the wilderness.",
 ref:"Numbers 14:34", quote:"after the number of the days in which ye searched the land, even forty days, each day for a year"},

{id:"num-003",book:"Numbers",section:"Torah",difficulty:"medium",
 q:"How were Korah, Dathan, and Abiram judged?",
 options:["Struck with leprosy","The earth opened and swallowed them","Consumed by serpents","Driven out of the camp"],
 answer:1,
 explain:"The ground clave asunder and swallowed them with their households. A separate fire consumed the 250 men who offered incense.",
 ref:"Numbers 16:32"},

{id:"num-004",book:"Numbers",section:"Torah",difficulty:"hard",
 q:"What did Aaron's rod produce as a sign of his priesthood?",
 options:["Figs","Buds, blossoms, and almonds","Olives","Pomegranates"],
 answer:1,
 explain:"Overnight, one dead staff among twelve budded and yielded ripe almonds \u2014 an unmistakable sign, and it was kept before the testimony as a token against rebels.",
 ref:"Numbers 17:8", quote:"and bloomed blossoms, and yielded almonds"},

{id:"num-005",book:"Numbers",section:"Torah",difficulty:"hard",
 q:"Why was Moses barred from entering the promised land?",
 options:["He struck the rock instead of speaking to it as commanded","He broke the first tablets","He married a foreign wife","He numbered the people without permission"],
 answer:0,
 explain:"God told him to speak to the rock; he struck it twice and took credit alongside Aaron. The stated verdict is that he did not believe God enough to sanctify him before the people.",
 ref:"Numbers 20:12"},

{id:"num-006",book:"Numbers",section:"Torah",difficulty:"medium",
 q:"What did Moses set on a pole to heal those bitten by serpents?",
 options:["A brasen serpent","A golden calf","A budding almond branch","A scarlet cord"],
 answer:0,
 explain:"Anyone bitten who looked at it lived. Centuries later Hezekiah destroyed it, because Israel had begun burning incense to it.",
 ref:"Numbers 21:9"},

{id:"num-007",book:"Numbers",section:"Torah",difficulty:"medium",
 q:"What unusual thing happened to Balaam on the road?",
 options:["His donkey spoke to him","He was struck blind for three days","His staff turned into a serpent","Fire fell from heaven beside him"],
 answer:0,
 explain:"The donkey saw the angel and turned aside three times; after Balaam struck her, the LORD opened her mouth. The prophet hired to curse Israel could see less than his animal.",
 ref:"Numbers 22:28"},

{id:"num-008",book:"Numbers",section:"Torah",difficulty:"hard",
 q:"How does the priestly blessing begin?",
 options:["\u201cBlessed be the God of Israel\u201d","\u201cThe LORD bless thee, and keep thee\u201d","\u201cPeace be unto thee, and to thy house\u201d","\u201cThe LORD is my shepherd\u201d"],
 answer:1,
 explain:"A three-part blessing Aaron and his sons were to put on the people. It is among the oldest biblical texts recovered archaeologically, found inscribed on silver amulets in Jerusalem.",
 ref:"Numbers 6:24", quote:"The LORD bless thee, and keep thee"},

/* ── DEUTERONOMY ───────────────────────────────────────── */
{id:"deu-001",book:"Deuteronomy",section:"Torah",difficulty:"easy",
 q:"How does the Shema begin?",
 options:["\u201cIn the beginning God created\u201d","\u201cHear, O Israel: The LORD our God is one LORD\u201d","\u201cBlessed is the man that walketh not\u201d","\u201cThe LORD is my light and my salvation\u201d"],
 answer:1,
 explain:"Shema is simply the Hebrew for \u2018hear.\u2019 It became Israel's central confession, recited twice daily, and Jesus cites it as the first commandment.",
 ref:"Deuteronomy 6:4", quote:"Hear, O Israel: The LORD our God is one LORD"},

{id:"deu-002",book:"Deuteronomy",section:"Torah",difficulty:"medium",
 q:"With what three things does Deuteronomy 6:5 say to love the LORD?",
 options:["Heart, soul, and might","Heart, mind, and strength","Soul, spirit, and body","Word, deed, and thought"],
 answer:0,
 explain:"The Hebrew triad is heart, soul, and might. The Gospels expand it with \u2018mind\u2019 when quoting it \u2014 which is why the four-part version feels familiar.",
 ref:"Deuteronomy 6:5", quote:"thou shalt love the LORD thy God with all thine heart, and with all thy soul, and with all thy might"},

{id:"deu-003",book:"Deuteronomy",section:"Torah",difficulty:"hard",
 q:"Which words did Jesus quote from Deuteronomy when tempted to turn stones to bread?",
 options:["\u201cThou shalt not tempt the LORD thy God\u201d","\u201cMan doth not live by bread only\u201d","\u201cThou shalt worship the LORD thy God\u201d","\u201cThe just shall live by his faith\u201d"],
 answer:1,
 explain:"All three of Jesus' replies in the wilderness come from Deuteronomy, but this is the one answering the bread temptation. \u2018The just shall live by his faith\u2019 is Habakkuk.",
 ref:"Deuteronomy 8:3", quote:"that he might make thee know that man doth not live by bread only"},

{id:"deu-004",book:"Deuteronomy",section:"Torah",difficulty:"hard",
 q:"On which two mountains were the blessing and the curse set?",
 options:["Sinai and Horeb","Gerizim and Ebal","Carmel and Tabor","Nebo and Pisgah"],
 answer:1,
 explain:"The blessing on Gerizim, the curse on Ebal, with the tribes divided between them. Sinai and Horeb are two names for the same mountain, which makes that option a trap.",
 ref:"Deuteronomy 11:29"},

{id:"deu-005",book:"Deuteronomy",section:"Torah",difficulty:"medium",
 q:"From what mountain did Moses view the promised land?",
 options:["Mount Sinai","Mount Nebo, to the top of Pisgah","Mount Carmel","Mount Hermon"],
 answer:1,
 explain:"He was shown the whole land from Gilead to the western sea, and told he would not cross over. He died there in the land of Moab.",
 ref:"Deuteronomy 34:1"},

{id:"deu-006",book:"Deuteronomy",section:"Torah",difficulty:"medium",
 q:"How old was Moses when he died, and in what condition?",
 options:["A hundred and twenty, with undimmed eye and unabated strength","Eighty, blind and frail","A hundred, and lame from the wrestling at Peniel","Ninety-nine, deaf and weak"],
 answer:0,
 explain:"The text is emphatic that his death was not from decline: his eye was not dim, nor his natural force abated.",
 ref:"Deuteronomy 34:7", quote:"his eye was not dim, nor his natural force abated"},

{id:"deu-007",book:"Deuteronomy",section:"Torah",difficulty:"hard",
 q:"What does Deuteronomy say about Moses' burial place?",
 options:["He was buried at Hebron with the patriarchs","No man knoweth of his sepulchre unto this day","He was buried beneath the tabernacle","He left no body, having been taken up"],
 answer:1,
 explain:"He was buried in a valley in Moab, but the location was never known. Being taken up without death is Enoch and Elijah, not Moses \u2014 the text says plainly that Moses died.",
 ref:"Deuteronomy 34:6", quote:"but no man knoweth of his sepulchre unto this day"},

/* ── HISTORICAL BOOKS ──────────────────────────────────── */
{id:"jos-001",book:"Joshua",section:"Historical",difficulty:"medium",
 q:"What sign did Rahab hang from her window?",
 options:["A lamp","A line of scarlet thread","A white cloth","A branch of hyssop"],
 answer:1,
 explain:"The spies instructed her to bind the scarlet line in the window so her household would be spared \u2014 an echo of the Passover blood on the doorposts.",
 ref:"Joshua 2:18", quote:"thou shalt bind this line of scarlet thread in the window"},

{id:"jos-002",book:"Joshua",section:"Historical",difficulty:"medium",
 q:"How was Jericho encircled before its walls fell?",
 options:["Once daily for six days, then seven times on the seventh","Seven times each day for seven days","Three times on a single day","Continuously for forty days"],
 answer:0,
 explain:"Once a day for six days, then seven circuits on the seventh, followed by the trumpets and the shout. Sevens saturate the account: seven priests, seven trumpets, seven days.",
 ref:"Joshua 6:3-4"},

{id:"jos-003",book:"Joshua",section:"Historical",difficulty:"hard",
 q:"Whose sin caused Israel's defeat at Ai?",
 options:["Achan, who took of the accursed thing","Caleb, who spared a Canaanite city","Phinehas, who broke the fast","Eleazar, who neglected the sacrifice"],
 answer:0,
 explain:"Achan took a Babylonish garment, silver, and a wedge of gold from Jericho's devoted spoil. The corporate consequence \u2014 the whole army defeated for one man's act \u2014 is the point of the episode.",
 ref:"Joshua 7:1"},

{id:"jdg-001",book:"Judges",section:"Historical",difficulty:"medium",
 q:"To how many men was Gideon's army reduced?",
 options:["Twelve","Three hundred","One thousand","Seven thousand"],
 answer:1,
 explain:"Reduced from thirty-two thousand, first by dismissing the fearful, then by the test at the water. The stated reason is so Israel could not claim its own hand had saved it.",
 ref:"Judges 7:7"},

{id:"jdg-002",book:"Judges",section:"Historical",difficulty:"medium",
 q:"What did Samson tell Delilah was the secret of his strength?",
 options:["His vow never to drink wine","That no razor had come upon his head, being a Nazarite from the womb","A ring he wore on his hand","That he had never touched a dead body"],
 answer:1,
 explain:"The hair was the visible sign of the Nazarite vow, which also included abstaining from wine and corpses. When it was cut, the text says the LORD had departed from him.",
 ref:"Judges 16:17"},

{id:"rut-001",book:"Ruth",section:"Historical",difficulty:"easy",
 q:"To whom did Ruth say \u201cwhither thou goest, I will go\u201d?",
 options:["Boaz","Naomi","Orpah","Obed"],
 answer:1,
 explain:"Spoken to her mother-in-law Naomi on the road back to Judah, not to a husband \u2014 which is worth noting, given how often the line is read at weddings. Orpah is the sister-in-law who turned back.",
 ref:"Ruth 1:16", quote:"whither thou goest, I will go"},

{id:"1sa-001",book:"1 Samuel",section:"Historical",difficulty:"medium",
 q:"How did the boy Samuel answer the LORD's call?",
 options:["\u201cHere am I; send me\u201d","\u201cSpeak, LORD; for thy servant heareth\u201d","\u201cWho am I, that I should go?\u201d","\u201cI am a child, and cannot speak\u201d"],
 answer:1,
 explain:"Eli taught him the words after the third call. \u2018Here am I; send me\u2019 is Isaiah's response in his temple vision, and \u2018I am a child\u2019 is Jeremiah's objection.",
 ref:"1 Samuel 3:10", quote:"Speak; for thy servant heareth"},

{id:"1sa-002",book:"1 Samuel",section:"Historical",difficulty:"medium",
 q:"With what did David strike Goliath?",
 options:["A sling and a stone","Goliath's own spear","A bow and arrow","A shepherd's staff"],
 answer:0,
 explain:"The stone from the sling sank into his forehead. David then used Goliath's own sword to cut off his head \u2014 but the felling blow was the stone.",
 ref:"1 Samuel 17:49"},

{id:"1sa-003",book:"1 Samuel",section:"Historical",difficulty:"hard",
 q:"What reason did God give Samuel for choosing David over his elder brothers?",
 options:["David was the firstborn of Jesse's second wife","Man looketh on the outward appearance, but the LORD looketh on the heart","David alone had kept the law of Moses","David was the tallest of the brothers"],
 answer:1,
 explain:"Said when Samuel was impressed by Eliab's appearance. There is deliberate irony here \u2014 Saul had been chosen partly for his height, and that had not gone well.",
 ref:"1 Samuel 16:7", quote:"for man looketh on the outward appearance, but the LORD looketh on the heart"},

{id:"2sa-001",book:"2 Samuel",section:"Historical",difficulty:"medium",
 q:"What did Nathan say to David after telling him the parable of the ewe lamb?",
 options:["\u201cThou art the man\u201d","\u201cThe LORD hath forsaken thee\u201d","\u201cRepent, and thou shalt live\u201d","\u201cWho hath required this at thine hand?\u201d"],
 answer:0,
 explain:"David condemned the rich man in the parable before realizing he had sentenced himself. The parable's power is that it gets a verdict out of him before he sees the application.",
 ref:"2 Samuel 12:7", quote:"And Nathan said to David, Thou art the man."},

{id:"1ki-001",book:"1 Kings",section:"Historical",difficulty:"medium",
 q:"What did Solomon ask God for at Gibeon?",
 options:["Long life","An understanding heart to judge the people","Victory over his enemies","Riches for the temple"],
 answer:1,
 explain:"Because he asked for discernment rather than long life, riches, or the death of his enemies, God granted him those things as well.",
 ref:"1 Kings 3:9", quote:"Give therefore thy servant an understanding heart to judge thy people"},

{id:"1ki-002",book:"1 Kings",section:"Historical",difficulty:"medium",
 q:"How was Elijah's contest on Mount Carmel decided?",
 options:["By lot before the elders","By which God answered by fire","By a drought lasting seven years","By the strength of the two armies"],
 answer:1,
 explain:"Elijah drenched his altar with water; fire fell and consumed the sacrifice, wood, stones, dust, and the water in the trench. Baal's prophets had cried and cut themselves from morning to noon with no answer.",
 ref:"1 Kings 18:24"},

{id:"1ki-003",book:"1 Kings",section:"Historical",difficulty:"hard",
 q:"How did God reveal himself to Elijah at Horeb, after the wind, earthquake, and fire?",
 options:["In a still small voice","In a pillar of cloud","In a vision of the throne","In a whirlwind of chariots"],
 answer:0,
 explain:"The text is explicit that the LORD was not in the wind, the earthquake, or the fire. The revelation comes in near-silence, immediately after the most spectacular display of Elijah's career.",
 ref:"1 Kings 19:12", quote:"and after the fire a still small voice"},

{id:"2ki-001",book:"2 Kings",section:"Historical",difficulty:"medium",
 q:"How was Elijah taken from Elisha?",
 options:["He died and was buried at Bethel","By a whirlwind, with a chariot of fire and horses of fire","He walked into the wilderness and vanished","He was carried off by the king's men"],
 answer:1,
 explain:"The chariot and horses of fire parted the two men; the whirlwind is what took Elijah up. Elisha then received a double portion of his spirit and took up his mantle.",
 ref:"2 Kings 2:11"},

{id:"2ki-002",book:"2 Kings",section:"Historical",difficulty:"hard",
 q:"What was Naaman told to do to be cleansed of his leprosy?",
 options:["Offer a bullock at Samaria","Wash seven times in the Jordan","Fast for seven days","Bring silver and gold to the prophet"],
 answer:1,
 explain:"He was angry that the cure was so ordinary and that Elisha did not come out to him personally \u2014 his servants had to talk him into it.",
 ref:"2 Kings 5:10"},

{id:"neh-001",book:"Nehemiah",section:"Historical",difficulty:"hard",
 q:"In how many days was the wall of Jerusalem finished under Nehemiah?",
 options:["Fifty-two days","Seven months","Three years","Forty days"],
 answer:0,
 explain:"The speed itself was the sign: the surrounding nations perceived the work had been done by God. Nehemiah had been cupbearer to Artaxerxes before requesting leave to rebuild.",
 ref:"Nehemiah 6:15"},

{id:"est-001",book:"Esther",section:"Historical",difficulty:"medium",
 q:"How did Mordecai urge Esther to approach the king?",
 options:["\u201cThe LORD will fight for thee\u201d","\u201cWho knoweth whether thou art come to the kingdom for such a time as this?\u201d","\u201cBe strong and of a good courage\u201d","\u201cFear not, for I have redeemed thee\u201d"],
 answer:1,
 explain:"Notable in a book that never names God directly \u2014 Mordecai's argument turns on providence without stating it outright.",
 ref:"Esther 4:14", quote:"who knoweth whether thou art come to the kingdom for such a time as this?"},

/* ── WISDOM & POETRY ───────────────────────────────────── */
{id:"job-001",book:"Job",section:"Wisdom",difficulty:"medium",
 q:"What did Job say after losing his children and possessions?",
 options:["\u201cWhy hast thou forsaken me?\u201d","\u201cThe LORD gave, and the LORD hath taken away; blessed be the name of the LORD\u201d","\u201cLet the day perish wherein I was born\u201d","\u201cI know that my redeemer liveth\u201d"],
 answer:1,
 explain:"His first response is worship. The curse on his birthday comes in chapter 3, after seven days of silence \u2014 both are his, but in that order.",
 ref:"Job 1:21", quote:"the LORD gave, and the LORD hath taken away; blessed be the name of the LORD"},

{id:"job-002",book:"Job",section:"Wisdom",difficulty:"hard",
 q:"How does God finally answer Job?",
 options:["By explaining the wager with Satan","Out of the whirlwind, with questions about creation","Through a fourth friend, Elihu","By restoring his health without speaking"],
 answer:1,
 explain:"God never explains the reason for Job's suffering. Instead he asks where Job was when the foundations of the earth were laid \u2014 the answer is an encounter, not an explanation.",
 ref:"Job 38:4"},

{id:"psa-001",book:"Psalms",section:"Wisdom",difficulty:"easy",
 q:"How does Psalm 23 open?",
 options:["\u201cThe LORD is my light and my salvation\u201d","\u201cThe LORD is my shepherd; I shall not want\u201d","\u201cBless the LORD, O my soul\u201d","\u201cThe heavens declare the glory of God\u201d"],
 answer:1,
 explain:"The other three are also genuine psalm openings \u2014 27, 103, and 19 respectively.",
 ref:"Psalms 23:1", quote:"The LORD is my shepherd; I shall not want."},

{id:"psa-002",book:"Psalms",section:"Wisdom",difficulty:"hard",
 q:"Which psalm is David's confession after Nathan confronted him over Bathsheba?",
 options:["Psalm 22","Psalm 51","Psalm 88","Psalm 137"],
 answer:1,
 explain:"Its superscription names the occasion directly. Psalm 22 is the psalm of dereliction quoted from the cross; 137 is the exile lament by the rivers of Babylon.",
 ref:"Psalms 51:10", quote:"Create in me a clean heart, O God"},

{id:"pro-001",book:"Proverbs",section:"Wisdom",difficulty:"medium",
 q:"According to Proverbs, what is the beginning of knowledge?",
 options:["The fear of the LORD","The counsel of the elders","The study of the law","A humble spirit"],
 answer:0,
 explain:"Stated at the outset as the book's premise, and repeated later with \u2018wisdom\u2019 in place of \u2018knowledge.\u2019 The clause that follows is that fools despise wisdom and instruction.",
 ref:"Proverbs 1:7", quote:"The fear of the LORD is the beginning of knowledge"},

{id:"ecc-001",book:"Ecclesiastes",section:"Wisdom",difficulty:"medium",
 q:"How does the Preacher's argument in Ecclesiastes begin?",
 options:["\u201cVanity of vanities; all is vanity\u201d","\u201cThere is a time to every purpose\u201d","\u201cRemember now thy Creator\u201d","\u201cTwo are better than one\u201d"],
 answer:0,
 explain:"The refrain frames the whole book. The Hebrew word suggests vapour or breath \u2014 not worthlessness so much as fleetingness. The others are all from Ecclesiastes too, but later.",
 ref:"Ecclesiastes 1:2", quote:"Vanity of vanities, saith the Preacher, vanity of vanities; all is vanity."},

/* ── PROPHETS ──────────────────────────────────────────── */
{id:"isa-001",book:"Isaiah",section:"Prophets",difficulty:"medium",
 q:"How did Isaiah respond to the LORD's question \u201cWhom shall I send?\u201d",
 options:["\u201cI am a child, and cannot speak\u201d","\u201cHere am I; send me\u201d","\u201cSend by the hand of him whom thou wilt send\u201d","\u201cSpeak, LORD; for thy servant heareth\u201d"],
 answer:1,
 explain:"His volunteering follows the cleansing of his lips with a coal from the altar. The reluctant reply about sending someone else is Moses at the bush; the child objection is Jeremiah.",
 ref:"Isaiah 6:8", quote:"Here am I; send me"},

{id:"isa-002",book:"Isaiah",section:"Prophets",difficulty:"medium",
 q:"Which titles does Isaiah 9:6 give to the promised child?",
 options:["Wonderful, Counsellor, The mighty God, The everlasting Father, The Prince of Peace","King of kings and Lord of lords","The Lion of the tribe of Judah","The Alpha and the Omega"],
 answer:0,
 explain:"The other three titles are genuine biblical language, but they come from Revelation, not Isaiah.",
 ref:"Isaiah 9:6", quote:"his name shall be called Wonderful, Counsellor, The mighty God, The everlasting Father, The Prince of Peace"},

{id:"isa-003",book:"Isaiah",section:"Prophets",difficulty:"hard",
 q:"How does Isaiah 53 describe the suffering servant?",
 options:["\u201cHe shall reign in majesty over all nations\u201d","\u201cHe was wounded for our transgressions, he was bruised for our iniquities\u201d","\u201cHe shall come with ten thousands of his saints\u201d","\u201cHis throne is established from of old\u201d"],
 answer:1,
 explain:"The chapter's logic is substitution: the punishment that brought peace fell on him, and by his stripes came healing.",
 ref:"Isaiah 53:5", quote:"But he was wounded for our transgressions, he was bruised for our iniquities"},

{id:"jer-001",book:"Jeremiah",section:"Prophets",difficulty:"hard",
 q:"What distinguishes the new covenant Jeremiah promises?",
 options:["It will be sealed with a new sign in the flesh","God will put his law in their inward parts and write it in their hearts","It will be established only with the tribe of Judah","It will require a new temple before it begins"],
 answer:1,
 explain:"Internal rather than external \u2014 and with it, that all shall know the LORD and their sin be remembered no more. Hebrews quotes this passage at length.",
 ref:"Jeremiah 31:33", quote:"I will put my law in their inward parts, and write it in their hearts"},

{id:"eze-001",book:"Ezekiel",section:"Prophets",difficulty:"medium",
 q:"What did Ezekiel see in the valley, and what did it represent?",
 options:["A field of wheat, representing the harvest of nations","Dry bones that came together and lived, representing the whole house of Israel","A vine withering, representing Judah's kings","A river flowing from the temple, representing the law"],
 answer:1,
 explain:"God gives the interpretation directly: the bones are the whole house of Israel, saying their hope is lost. The vision is about national restoration from exile.",
 ref:"Ezekiel 37:11"},

{id:"dan-001",book:"Daniel",section:"Prophets",difficulty:"medium",
 q:"Who was cast into the fiery furnace?",
 options:["Daniel alone","Shadrach, Meshach, and Abednego","Daniel and his three friends together","Belshazzar's counsellors"],
 answer:1,
 explain:"Daniel is not in the furnace account \u2014 he faces the lions' den, under Darius, several chapters later. Two famous stories, two different sets of people and kings.",
 ref:"Daniel 3:20"},

{id:"dan-002",book:"Daniel",section:"Prophets",difficulty:"hard",
 q:"Why was Daniel thrown into the lions' den?",
 options:["He refused to bow to a golden image","He continued praying toward Jerusalem, against a decree forbidding petitions to any god or man but the king","He interpreted a dream unfavourably","He refused the king's meat and wine"],
 answer:1,
 explain:"The decree was engineered by officials who could find no fault in him except concerning the law of his God. Refusing the image is the furnace story; the king's meat is chapter 1.",
 ref:"Daniel 6:10"},

{id:"jon-001",book:"Jonah",section:"Prophets",difficulty:"medium",
 q:"What swallowed Jonah, and for how long?",
 options:["A whale, for seven days","A great fish, for three days and three nights","A sea serpent, for one night","A leviathan, for forty days"],
 answer:1,
 explain:"The text says a great fish \u2014 never a whale. That detail comes from later translation and retelling.",
 ref:"Jonah 1:17", quote:"Now the LORD had prepared a great fish to swallow up Jonah"},

{id:"jon-002",book:"Jonah",section:"Prophets",difficulty:"hard",
 q:"Why was Jonah angry after Nineveh repented?",
 options:["The people mocked his message","He knew God was gracious and merciful, and would relent from the destruction he had preached","He was denied payment by the king","His prophecy was misquoted by the elders"],
 answer:1,
 explain:"He says outright that this is why he fled to Tarshish in the first place. His problem was never fear of failure \u2014 it was fear that his enemies would be spared.",
 ref:"Jonah 4:2"},

{id:"mic-001",book:"Micah",section:"Prophets",difficulty:"medium",
 q:"What does Micah say the LORD requires?",
 options:["Burnt offerings and thousands of rams","To do justly, to love mercy, and to walk humbly with thy God","To keep the feasts and new moons","To build again the house of the LORD"],
 answer:1,
 explain:"It answers the preceding question about whether God wants ever-escalating sacrifice. The reply reduces the requirement to three things, none of them ritual.",
 ref:"Micah 6:8", quote:"to do justly, and to love mercy, and to walk humbly with thy God"},

{id:"mal-001",book:"Malachi",section:"Prophets",difficulty:"hard",
 q:"With what promise does Malachi \u2014 and the Old Testament \u2014 close?",
 options:["The rebuilding of the temple","The sending of Elijah the prophet before the great and dreadful day of the LORD","The return of the exiles from Babylon","The coming of a new king from David's line"],
 answer:1,
 explain:"The final words concern turning the hearts of fathers and children to one another. In Christian ordering this is the last verse of the Old Testament, and the Gospels connect the promise to John the Baptist.",
 ref:"Malachi 4:5", quote:"Behold, I will send you Elijah the prophet before the coming of the great and dreadful day of the LORD"},

{id:"hab-001",book:"Habakkuk",section:"Prophets",difficulty:"hard",
 q:"Which phrase from Habakkuk became central to Paul's argument in Romans?",
 options:["\u201cThe just shall live by his faith\u201d","\u201cThe LORD is in his holy temple\u201d","\u201cWrite the vision, and make it plain\u201d","\u201cThe earth shall be filled with the knowledge of the glory of the LORD\u201d"],
 answer:0,
 explain:"Quoted in Romans, Galatians, and Hebrews, and later a hinge text of the Reformation. The other three phrases are all genuinely from Habakkuk.",
 ref:"Habakkuk 2:4", quote:"but the just shall live by his faith"},

{id:"amo-001",book:"Amos",section:"Prophets",difficulty:"hard",
 q:"What was Amos' occupation before he prophesied?",
 options:["A priest at Bethel","A herdman and a gatherer of sycomore fruit","A scribe in the king's court","A Levite singer"],
 answer:1,
 explain:"He says plainly that he was no prophet, nor a prophet's son, but was taken from following the flock. Amaziah, the priest at Bethel, is the one who tries to expel him.",
 ref:"Amos 7:14", quote:"I was no prophet, neither was I a prophet's son; but I was an herdman, and a gatherer of sycomore fruit"}

];
